/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
/**
 * Function that generates a random uuid.
 * If used with an argument of type string, it generates a Sha256 with the input and then transforms it to uuid.
 */
export function uuid(s?: string | undefined | null): string
